// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {mod} from '../models';
import {cost} from '../models';
import {sshutil} from '../models';
import {time} from '../models';

export function AIChatStream(arg1:string,arg2:string,arg3:Array<main.AIChatMessage>):Promise<void>;

export function AICostOptimization():Promise<void>;

export function AIGenerateTemplate(arg1:string):Promise<void>;

export function AIRecommendTemplates(arg1:string):Promise<void>;

export function AnalyzeCaseError(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function AnalyzeDeploymentError(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function BatchDeleteCustomDeployments(arg1:Array<string>):Promise<Array<mod.BatchOperationResult>>;

export function BatchStartCustomDeployments(arg1:Array<string>):Promise<Array<mod.BatchOperationResult>>;

export function BatchStopCustomDeployments(arg1:Array<string>):Promise<Array<mod.BatchOperationResult>>;

export function CancelScheduledTask(arg1:string):Promise<void>;

export function CheckForUpdates():Promise<main.VersionCheckResult>;

export function CloseTerminal(arg1:string):Promise<void>;

export function ComposeDown(arg1:string,arg2:Array<string>):Promise<void>;

export function ComposePreview(arg1:string,arg2:Array<string>):Promise<main.ComposeSummary>;

export function ComposeUp(arg1:string,arg2:Array<string>):Promise<void>;

export function CopyFileTo(arg1:string,arg2:string):Promise<void>;

export function CopyTemplate(arg1:string,arg2:string):Promise<void>;

export function CreateAndRunCase(arg1:string,arg2:string,arg3:Record<string, string>):Promise<void>;

export function CreateCase(arg1:string,arg2:string,arg3:Record<string, string>):Promise<void>;

export function CreateCustomDeployment(arg1:mod.DeploymentConfig):Promise<mod.CustomDeployment>;

export function CreateProfile(arg1:string,arg2:string,arg3:string):Promise<mod.ProfileInfo>;

export function CreateProject(arg1:string):Promise<void>;

export function CreateRemoteDirectory(arg1:string,arg2:string):Promise<void>;

export function DeleteConfigTemplate(arg1:string):Promise<void>;

export function DeleteCustomDeployment(arg1:string):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function DeleteRemoteFile(arg1:string,arg2:string):Promise<void>;

export function DeployCase(arg1:string,arg2:string,arg3:Record<string, string>):Promise<void>;

export function DownloadFile(arg1:string,arg2:string,arg3:string):Promise<main.FileTransferResult>;

export function EstimateDeploymentCost(arg1:mod.DeploymentConfig):Promise<mod.CostEstimate>;

export function ExecCommand(arg1:string,arg2:string):Promise<main.ExecCommandResult>;

export function ExecUserdata(arg1:string,arg2:string):Promise<main.ExecCommandResult>;

export function ExportConfigTemplate(arg1:string,arg2:string):Promise<void>;

export function ExportTemplates(arg1:Array<string>):Promise<string>;

export function FetchRegistryTemplates(arg1:string):Promise<Array<main.RegistryTemplate>>;

export function FetchTemplateReadme(arg1:string,arg2:string):Promise<string>;

export function GetActiveProfile():Promise<mod.ProfileInfo>;

export function GetBalances(arg1:Array<string>):Promise<Array<main.BalanceInfo>>;

export function GetBaseTemplates():Promise<Array<mod.BaseTemplate>>;

export function GetBills(arg1:Array<string>):Promise<Array<main.BillInfo>>;

export function GetCaseOutputs(arg1:string):Promise<Record<string, string>>;

export function GetConfig():Promise<main.ConfigInfo>;

export function GetCostEstimate(arg1:string,arg2:Record<string, string>):Promise<cost.CostEstimate>;

export function GetCurrentProject():Promise<string>;

export function GetDeploymentHistory(arg1:string):Promise<Array<mod.DeploymentChangeHistory>>;

export function GetDisableRightClick():Promise<boolean>;

export function GetInstanceTypes(arg1:string,arg2:string):Promise<Array<mod.InstanceType>>;

export function GetLanguage():Promise<string>;

export function GetMCPStatus():Promise<main.MCPStatus>;

export function GetNotificationEnabled():Promise<boolean>;

export function GetPredictedMonthlyCost():Promise<string>;

export function GetProviderRegions(arg1:string):Promise<Array<mod.Region>>;

export function GetProvidersConfig(arg1:string):Promise<main.ProvidersConfigInfo>;

export function GetRemoteFileContent(arg1:string,arg2:string):Promise<string>;

export function GetResourceSummary():Promise<Array<main.ResourceSummary>>;

export function GetSSHInfoForCase(arg1:string):Promise<Record<string, any>>;

export function GetScheduledTask(arg1:string):Promise<mod.ScheduledTask>;

export function GetShowWelcomeDialog():Promise<boolean>;

export function GetTemplateFiles(arg1:string):Promise<Record<string, string>>;

export function GetTemplateMetadata(arg1:string):Promise<mod.BaseTemplate>;

export function GetTemplateVariables(arg1:string):Promise<Array<main.TemplateVariable>>;

export function GetTerraformMirrorConfig():Promise<main.TerraformMirrorConfig>;

export function GetTotalRuntime():Promise<string>;

export function GetVersion():Promise<string>;

export function ImportConfigTemplate(arg1:string,arg2:string):Promise<void>;

export function ImportTemplates(arg1:string):Promise<Array<string>>;

export function ListAllTemplates():Promise<Array<main.TemplateInfo>>;

export function ListCaseScheduledTasks(arg1:string):Promise<Array<mod.ScheduledTask>>;

export function ListCases():Promise<Array<main.CaseInfo>>;

export function ListComposeTemplates():Promise<Array<mod.ComposeTemplate>>;

export function ListConfigTemplates():Promise<Array<string>>;

export function ListCustomDeployments():Promise<Array<mod.CustomDeployment>>;

export function ListPortForwards():Promise<Array<main.PortForwardInfo>>;

export function ListProfiles():Promise<Array<mod.ProfileInfo>>;

export function ListProjects():Promise<Array<main.ProjectInfo>>;

export function ListRemoteFiles(arg1:string,arg2:string):Promise<Array<sshutil.FileInfo>>;

export function ListScheduledTasks():Promise<Array<mod.ScheduledTask>>;

export function ListTemplates():Promise<Array<main.TemplateInfo>>;

export function ListUserdataTemplates():Promise<Array<mod.UserdataTemplate>>;

export function LoadConfigTemplate(arg1:string):Promise<mod.DeploymentConfig>;

export function PullTemplate(arg1:string,arg2:boolean):Promise<void>;

export function RecommendTemplates(arg1:string):Promise<Array<main.TemplateRecommendation>>;

export function RemoveCase(arg1:string):Promise<void>;

export function RemoveTemplate(arg1:string):Promise<void>;

export function RenameRemoteFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SaveConfigTemplate(arg1:string,arg2:mod.DeploymentConfig):Promise<void>;

export function SaveProvidersConfig(arg1:string,arg2:Record<string, string>,arg3:string):Promise<void>;

export function SaveProxyConfig(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SaveTemplateFiles(arg1:string,arg2:Record<string, string>):Promise<string>;

export function SaveTerraformMirrorConfig(arg1:boolean,arg2:Array<string>,arg3:string,arg4:boolean):Promise<void>;

export function ScheduleTask(arg1:string,arg2:string,arg3:string,arg4:time.Time):Promise<mod.ScheduledTask>;

export function SelectComposeFile():Promise<string>;

export function SelectDirectory(arg1:string):Promise<string>;

export function SelectFile(arg1:string):Promise<string>;

export function SelectSaveFile(arg1:string,arg2:string):Promise<string>;

export function SetActiveProfile(arg1:string):Promise<mod.ProfileInfo>;

export function SetDebugLogging(arg1:boolean):Promise<void>;

export function SetDisableRightClick(arg1:boolean):Promise<void>;

export function SetLanguage(arg1:string):Promise<void>;

export function SetNotificationEnabled(arg1:boolean):Promise<void>;

export function SetShowWelcomeDialog(arg1:boolean):Promise<void>;

export function StartCase(arg1:string):Promise<void>;

export function StartCustomDeployment(arg1:string):Promise<void>;

export function StartMCPServer(arg1:string,arg2:string):Promise<void>;

export function StartPortForward(arg1:string,arg2:number,arg3:string,arg4:number):Promise<main.PortForwardInfo>;

export function StartSSHTerminal(arg1:string,arg2:number,arg3:number):Promise<string>;

export function StopCase(arg1:string):Promise<void>;

export function StopCustomDeployment(arg1:string):Promise<void>;

export function StopMCPServer():Promise<void>;

export function StopPortForward(arg1:string):Promise<void>;

export function SwitchProject(arg1:string):Promise<void>;

export function TestTerraformEndpoints():Promise<Array<main.EndpointCheck>>;

export function UpdateProfile(arg1:string,arg2:string,arg3:string,arg4:string):Promise<mod.ProfileInfo>;

export function UpdateProfileAIConfig(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function UploadFile(arg1:string,arg2:string,arg3:string):Promise<main.FileTransferResult>;

export function UploadUserdataScript(arg1:string,arg2:string,arg3:string):Promise<main.FileTransferResult>;

export function ValidateDeploymentConfig(arg1:mod.DeploymentConfig):Promise<mod.ValidationResult>;

export function WriteRemoteFileContent(arg1:string,arg2:string,arg3:string):Promise<void>;

export function WriteToTerminal(arg1:string,arg2:string):Promise<void>;
