// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/redc.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Case struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Id         string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name       string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type       string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Module     string                 `protobuf:"bytes,4,opt,name=module,proto3" json:"module,omitempty"`
	Operator   string                 `protobuf:"bytes,5,opt,name=operator,proto3" json:"operator,omitempty"`
	Path       string                 `protobuf:"bytes,6,opt,name=path,proto3" json:"path,omitempty"`
	Node       int32                  `protobuf:"varint,7,opt,name=node,proto3" json:"node,omitempty"`
	CreateTime string                 `protobuf:"bytes,8,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	StateTime  string                 `protobuf:"bytes,9,opt,name=state_time,json=stateTime,proto3" json:"state_time,omitempty"`
	Parameter  []string               `protobuf:"bytes,10,rep,name=parameter,proto3" json:"parameter,omitempty"`
	State      string                 `protobuf:"bytes,11,opt,name=state,proto3" json:"state,omitempty"`
	// Output 是 map[string]OutputMeta，这里简化存储为 JSON 字符串
	// 或者你可以定义一个 message OutputMeta 然后用 map<string, OutputMeta>
	OutputJson    string `protobuf:"bytes,12,opt,name=output_json,json=outputJson,proto3" json:"output_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Case) Reset() {
	*x = Case{}
	mi := &file_proto_redc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Case) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Case) ProtoMessage() {}

func (x *Case) ProtoReflect() protoreflect.Message {
	mi := &file_proto_redc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Case.ProtoReflect.Descriptor instead.
func (*Case) Descriptor() ([]byte, []int) {
	return file_proto_redc_proto_rawDescGZIP(), []int{0}
}

func (x *Case) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Case) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Case) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Case) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *Case) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *Case) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Case) GetNode() int32 {
	if x != nil {
		return x.Node
	}
	return 0
}

func (x *Case) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *Case) GetStateTime() string {
	if x != nil {
		return x.StateTime
	}
	return ""
}

func (x *Case) GetParameter() []string {
	if x != nil {
		return x.Parameter
	}
	return nil
}

func (x *Case) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Case) GetOutputJson() string {
	if x != nil {
		return x.OutputJson
	}
	return ""
}

type Project struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectName   string                 `protobuf:"bytes,1,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	ProjectPath   string                 `protobuf:"bytes,2,opt,name=project_path,json=projectPath,proto3" json:"project_path,omitempty"`
	CreateTime    string                 `protobuf:"bytes,3,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	User          string                 `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"` // 不存 Case 列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_proto_redc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_proto_redc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_proto_redc_proto_rawDescGZIP(), []int{1}
}

func (x *Project) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *Project) GetProjectPath() string {
	if x != nil {
		return x.ProjectPath
	}
	return ""
}

func (x *Project) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *Project) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

var File_proto_redc_proto protoreflect.FileDescriptor

const file_proto_redc_proto_rawDesc = "" +
	"\n" +
	"\x10proto/redc.proto\x12\x04redc\"\xaf\x02\n" +
	"\x04Case\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x16\n" +
	"\x06module\x18\x04 \x01(\tR\x06module\x12\x1a\n" +
	"\boperator\x18\x05 \x01(\tR\boperator\x12\x12\n" +
	"\x04path\x18\x06 \x01(\tR\x04path\x12\x12\n" +
	"\x04node\x18\a \x01(\x05R\x04node\x12\x1f\n" +
	"\vcreate_time\x18\b \x01(\tR\n" +
	"createTime\x12\x1d\n" +
	"\n" +
	"state_time\x18\t \x01(\tR\tstateTime\x12\x1c\n" +
	"\tparameter\x18\n" +
	" \x03(\tR\tparameter\x12\x14\n" +
	"\x05state\x18\v \x01(\tR\x05state\x12\x1f\n" +
	"\voutput_json\x18\f \x01(\tR\n" +
	"outputJson\"\x84\x01\n" +
	"\aProject\x12!\n" +
	"\fproject_name\x18\x01 \x01(\tR\vprojectName\x12!\n" +
	"\fproject_path\x18\x02 \x01(\tR\vprojectPath\x12\x1f\n" +
	"\vcreate_time\x18\x03 \x01(\tR\n" +
	"createTime\x12\x12\n" +
	"\x04user\x18\x04 \x01(\tR\x04userB\x0eZ\fred-cloud/pbb\x06proto3"

var (
	file_proto_redc_proto_rawDescOnce sync.Once
	file_proto_redc_proto_rawDescData []byte
)

func file_proto_redc_proto_rawDescGZIP() []byte {
	file_proto_redc_proto_rawDescOnce.Do(func() {
		file_proto_redc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_redc_proto_rawDesc), len(file_proto_redc_proto_rawDesc)))
	})
	return file_proto_redc_proto_rawDescData
}

var file_proto_redc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_redc_proto_goTypes = []any{
	(*Case)(nil),    // 0: redc.Case
	(*Project)(nil), // 1: redc.Project
}
var file_proto_redc_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_redc_proto_init() }
func file_proto_redc_proto_init() {
	if File_proto_redc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_redc_proto_rawDesc), len(file_proto_redc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_redc_proto_goTypes,
		DependencyIndexes: file_proto_redc_proto_depIdxs,
		MessageInfos:      file_proto_redc_proto_msgTypes,
	}.Build()
	File_proto_redc_proto = out.File
	file_proto_redc_proto_goTypes = nil
	file_proto_redc_proto_depIdxs = nil
}
