// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: proto/redc.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Case struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Id         string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name       string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type       string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Module     string                 `protobuf:"bytes,4,opt,name=module,proto3" json:"module,omitempty"`
	Operator   string                 `protobuf:"bytes,5,opt,name=operator,proto3" json:"operator,omitempty"`
	Path       string                 `protobuf:"bytes,6,opt,name=path,proto3" json:"path,omitempty"`
	Node       int32                  `protobuf:"varint,7,opt,name=node,proto3" json:"node,omitempty"`
	CreateTime string                 `protobuf:"bytes,8,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	StateTime  string                 `protobuf:"bytes,9,opt,name=state_time,json=stateTime,proto3" json:"state_time,omitempty"`
	Parameter  []string               `protobuf:"bytes,10,rep,name=parameter,proto3" json:"parameter,omitempty"`
	State      string                 `protobuf:"bytes,11,opt,name=state,proto3" json:"state,omitempty"`
	// Output 是 map[string]OutputMeta，这里简化存储为 JSON 字符串
	// 或者你可以定义一个 message OutputMeta 然后用 map<string, OutputMeta>
	OutputJson    string `protobuf:"bytes,12,opt,name=output_json,json=outputJson,proto3" json:"output_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Case) Reset() {
	*x = Case{}
	mi := &file_proto_redc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Case) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Case) ProtoMessage() {}

func (x *Case) ProtoReflect() protoreflect.Message {
	mi := &file_proto_redc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Case.ProtoReflect.Descriptor instead.
func (*Case) Descriptor() ([]byte, []int) {
	return file_proto_redc_proto_rawDescGZIP(), []int{0}
}

func (x *Case) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Case) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Case) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Case) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *Case) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *Case) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Case) GetNode() int32 {
	if x != nil {
		return x.Node
	}
	return 0
}

func (x *Case) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *Case) GetStateTime() string {
	if x != nil {
		return x.StateTime
	}
	return ""
}

func (x *Case) GetParameter() []string {
	if x != nil {
		return x.Parameter
	}
	return nil
}

func (x *Case) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Case) GetOutputJson() string {
	if x != nil {
		return x.OutputJson
	}
	return ""
}

type Project struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectName   string                 `protobuf:"bytes,1,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	ProjectPath   string                 `protobuf:"bytes,2,opt,name=project_path,json=projectPath,proto3" json:"project_path,omitempty"`
	CreateTime    string                 `protobuf:"bytes,3,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	User          string                 `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"` // 不存 Case 列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_proto_redc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_proto_redc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_proto_redc_proto_rawDescGZIP(), []int{1}
}

func (x *Project) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *Project) GetProjectPath() string {
	if x != nil {
		return x.ProjectPath
	}
	return ""
}

func (x *Project) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *Project) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

type CustomDeployment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TemplateName  string                 `protobuf:"bytes,3,opt,name=template_name,json=templateName,proto3" json:"template_name,omitempty"`
	ConfigJson    string                 `protobuf:"bytes,4,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"` // DeploymentConfig 序列化为 JSON
	State         string                 `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	OutputsJson   string                 `protobuf:"bytes,8,opt,name=outputs_json,json=outputsJson,proto3" json:"outputs_json,omitempty"` // map[string]interface{} 序列化为 JSON
	ProjectId     string                 `protobuf:"bytes,9,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomDeployment) Reset() {
	*x = CustomDeployment{}
	mi := &file_proto_redc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomDeployment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomDeployment) ProtoMessage() {}

func (x *CustomDeployment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_redc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomDeployment.ProtoReflect.Descriptor instead.
func (*CustomDeployment) Descriptor() ([]byte, []int) {
	return file_proto_redc_proto_rawDescGZIP(), []int{2}
}

func (x *CustomDeployment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CustomDeployment) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CustomDeployment) GetTemplateName() string {
	if x != nil {
		return x.TemplateName
	}
	return ""
}

func (x *CustomDeployment) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

func (x *CustomDeployment) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *CustomDeployment) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CustomDeployment) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *CustomDeployment) GetOutputsJson() string {
	if x != nil {
		return x.OutputsJson
	}
	return ""
}

func (x *CustomDeployment) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type DeploymentChangeHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DeploymentId  string                 `protobuf:"bytes,2,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	ChangeType    string                 `protobuf:"bytes,3,opt,name=change_type,json=changeType,proto3" json:"change_type,omitempty"`
	OldValueJson  string                 `protobuf:"bytes,4,opt,name=old_value_json,json=oldValueJson,proto3" json:"old_value_json,omitempty"` // map[string]interface{} 序列化为 JSON
	NewValueJson  string                 `protobuf:"bytes,5,opt,name=new_value_json,json=newValueJson,proto3" json:"new_value_json,omitempty"` // map[string]interface{} 序列化为 JSON
	Operator      string                 `protobuf:"bytes,6,opt,name=operator,proto3" json:"operator,omitempty"`
	Timestamp     string                 `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Description   string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	ProjectId     string                 `protobuf:"bytes,9,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeploymentChangeHistory) Reset() {
	*x = DeploymentChangeHistory{}
	mi := &file_proto_redc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeploymentChangeHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeploymentChangeHistory) ProtoMessage() {}

func (x *DeploymentChangeHistory) ProtoReflect() protoreflect.Message {
	mi := &file_proto_redc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeploymentChangeHistory.ProtoReflect.Descriptor instead.
func (*DeploymentChangeHistory) Descriptor() ([]byte, []int) {
	return file_proto_redc_proto_rawDescGZIP(), []int{3}
}

func (x *DeploymentChangeHistory) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeploymentChangeHistory) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *DeploymentChangeHistory) GetChangeType() string {
	if x != nil {
		return x.ChangeType
	}
	return ""
}

func (x *DeploymentChangeHistory) GetOldValueJson() string {
	if x != nil {
		return x.OldValueJson
	}
	return ""
}

func (x *DeploymentChangeHistory) GetNewValueJson() string {
	if x != nil {
		return x.NewValueJson
	}
	return ""
}

func (x *DeploymentChangeHistory) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *DeploymentChangeHistory) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *DeploymentChangeHistory) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DeploymentChangeHistory) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

var File_proto_redc_proto protoreflect.FileDescriptor

const file_proto_redc_proto_rawDesc = "" +
	"\n" +
	"\x10proto/redc.proto\x12\x04redc\"\xaf\x02\n" +
	"\x04Case\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x16\n" +
	"\x06module\x18\x04 \x01(\tR\x06module\x12\x1a\n" +
	"\boperator\x18\x05 \x01(\tR\boperator\x12\x12\n" +
	"\x04path\x18\x06 \x01(\tR\x04path\x12\x12\n" +
	"\x04node\x18\a \x01(\x05R\x04node\x12\x1f\n" +
	"\vcreate_time\x18\b \x01(\tR\n" +
	"createTime\x12\x1d\n" +
	"\n" +
	"state_time\x18\t \x01(\tR\tstateTime\x12\x1c\n" +
	"\tparameter\x18\n" +
	" \x03(\tR\tparameter\x12\x14\n" +
	"\x05state\x18\v \x01(\tR\x05state\x12\x1f\n" +
	"\voutput_json\x18\f \x01(\tR\n" +
	"outputJson\"\x84\x01\n" +
	"\aProject\x12!\n" +
	"\fproject_name\x18\x01 \x01(\tR\vprojectName\x12!\n" +
	"\fproject_path\x18\x02 \x01(\tR\vprojectPath\x12\x1f\n" +
	"\vcreate_time\x18\x03 \x01(\tR\n" +
	"createTime\x12\x12\n" +
	"\x04user\x18\x04 \x01(\tR\x04user\"\x92\x02\n" +
	"\x10CustomDeployment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12#\n" +
	"\rtemplate_name\x18\x03 \x01(\tR\ftemplateName\x12\x1f\n" +
	"\vconfig_json\x18\x04 \x01(\tR\n" +
	"configJson\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\x12!\n" +
	"\foutputs_json\x18\b \x01(\tR\voutputsJson\x12\x1d\n" +
	"\n" +
	"project_id\x18\t \x01(\tR\tprojectId\"\xb6\x02\n" +
	"\x17DeploymentChangeHistory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rdeployment_id\x18\x02 \x01(\tR\fdeploymentId\x12\x1f\n" +
	"\vchange_type\x18\x03 \x01(\tR\n" +
	"changeType\x12$\n" +
	"\x0eold_value_json\x18\x04 \x01(\tR\foldValueJson\x12$\n" +
	"\x0enew_value_json\x18\x05 \x01(\tR\fnewValueJson\x12\x1a\n" +
	"\boperator\x18\x06 \x01(\tR\boperator\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\tR\ttimestamp\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"project_id\x18\t \x01(\tR\tprojectIdB\x0eZ\fred-cloud/pbb\x06proto3"

var (
	file_proto_redc_proto_rawDescOnce sync.Once
	file_proto_redc_proto_rawDescData []byte
)

func file_proto_redc_proto_rawDescGZIP() []byte {
	file_proto_redc_proto_rawDescOnce.Do(func() {
		file_proto_redc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_redc_proto_rawDesc), len(file_proto_redc_proto_rawDesc)))
	})
	return file_proto_redc_proto_rawDescData
}

var file_proto_redc_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_redc_proto_goTypes = []any{
	(*Case)(nil),                    // 0: redc.Case
	(*Project)(nil),                 // 1: redc.Project
	(*CustomDeployment)(nil),        // 2: redc.CustomDeployment
	(*DeploymentChangeHistory)(nil), // 3: redc.DeploymentChangeHistory
}
var file_proto_redc_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_redc_proto_init() }
func file_proto_redc_proto_init() {
	if File_proto_redc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_redc_proto_rawDesc), len(file_proto_redc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_redc_proto_goTypes,
		DependencyIndexes: file_proto_redc_proto_depIdxs,
		MessageInfos:      file_proto_redc_proto_msgTypes,
	}.Build()
	File_proto_redc_proto = out.File
	file_proto_redc_proto_goTypes = nil
	file_proto_redc_proto_depIdxs = nil
}
