version: "3.9"

# ==============================================================================
# 1. Configs: 全局配置中心
# 作用: 定义可复用的静态资源，redc 会将其注入到 Terraform 变量中
# ==============================================================================
configs:
  # [文件型] SSH 公钥
  admin_ssh_key:
    file: ~/.ssh/id_rsa.pub

  # [结构型] 安全组白名单 (将被序列化为 JSON 传递)
  global_whitelist:
    rules:
      - port: 22
        cidr: 1.2.3.4/32
        desc: "Admin Access"
      - port: 80
        cidr: 0.0.0.0/0
        desc: "HTTP Listener"
      - port: 443
        cidr: 0.0.0.0/0
        desc: "HTTPS Listener"

# ==============================================================================
# 2. Plugins: 插件服务 (非计算资源)
# 作用: 独立于服务器的云资源，如 DNS 解析、对象存储、VPC 对等连接等
# ==============================================================================
plugins:
  # 插件 A: 阿里云 DNS 解析
  # 场景: 基础设施启动后，自动将域名指向 Teamserver IP
  dns_record:
    image: plugin-dns-aliyun
    # 引用外部定义的 provider 名称
    provider: ali_hk_main
    environment:
      - domain=redteam-ops.com
      - record=cs
      - type=A
      - value=${teamserver.outputs.public_ip}

  # 插件 B: AWS S3 存储桶 (Loot Box)
  # 场景: 仅在生产环境 ('prod') 启用，用于存放回传数据
  loot_bucket:
    image: plugin-s3
    profiles:
      - prod
    provider: aws_us_east
    environment:
      - bucket_name=rt-ops-2026-logs
      - acl=private

# ==============================================================================
# 3. Services: Case场景
# ==============================================================================
services:

  # ---------------------------------------------------------------------------
  # Service A: 核心控制端 (Teamserver)
  # 特性: 总是启动 (无 profile)，包含完整生命周期钩子和文件流转
  # ---------------------------------------------------------------------------
  teamserver:
    image: ecs
    provider: ali_hk_main
    container_name: ts_leader

    # [Configs] 注入全局配置 (tf_var=config_key)
    configs:
      - ssh_public_key=admin_ssh_key
      - security_rules=global_whitelist

    environment:
      - password=StrongPassword123!
      - region=ap-southeast-1

    # [Volumes] 文件上传 (Local -> Remote)
    # 机器 SSH 连通后立即执行
    volumes:
      - ./tools/cobaltstrike.jar:/root/cs/cobaltstrike.jar
      - ./profiles/amazon.profile:/root/cs/c2.profile
      - ./scripts/init_server.sh:/root/init.sh

    # [Command] 实例内部自启动
    command: |
      chmod +x /root/init.sh
      /root/init.sh start --profile /root/cs/c2.profile

    # [Downloads] 文件回传 (Remote -> Local)
    # 启动完成后抓取凭证
    downloads:
      - /root/cs/.cobaltstrike.beacon_keys:./loot/beacon.keys
      - /root/cs/teamserver.prop:./loot/ts.prop

  # ---------------------------------------------------------------------------
  # Service B: 全球代理矩阵 (Global Redirectors)
  # 特性: 矩阵部署 (Matrix Deployment) + Profiles
  # ---------------------------------------------------------------------------
  global_redirectors:
    image: nginx-proxy

    # [Profiles] 仅在指定模式下启动 (e.g., redc up --profile prod)
    profiles:
      - prod

    # [Matrix] 多 Provider 引用
    # redc 会自动裂变出:
    # 1. global_redirectors_aws_us_east
    # 2. global_redirectors_tencent_sg
    # 3. global_redirectors_ali_jp (假设 providers.yaml 里有这个)
    provider:
      - aws_us_east
      - tencent_sg
      - ali_jp

    depends_on:
      - teamserver

    configs:
      - ingress_rules=global_whitelist

    # 注入当前 provider 的别名
    environment:
      - upstream_ip=${teamserver.outputs.public_ip}
      - node_tag=${provider.alias}

    command: docker run -d -p 80:80 -e UPSTREAM=${teamserver.outputs.public_ip} nginx-proxy

  # ---------------------------------------------------------------------------
  # Service C: 攻击/扫描节点
  # 特性: 攻击模式专用
  # ---------------------------------------------------------------------------
  scan_workers:
    image: aws-ec2-spot
    profiles:
      - attack
    deploy:
      replicas: 5
    provider: aws_us_east
    command: /app/run_scan.sh

# ==============================================================================
# 4. Setup: 联合编排 (Post-Deployment Hooks)
# 作用: 基础设施全部 Ready 后，执行跨机器的注册/交互逻辑
# 注意: redc 会根据当前激活的 Profile 自动跳过未启动服务的相关任务
# ==============================================================================
setup:

  # 任务 1: 基础检查 (总是执行)
  - name: "检查 Teamserver 状态"
    service: teamserver
    command: ./ts_cli status

  # 任务 2: 注册 AWS 代理 (仅 prod 模式有效)
  # 引用裂变后的实例名称: {service}_{provider}
  - name: "注册 AWS 代理节点"
    service: teamserver
    command: >
      ./aggressor_cmd listener_create 
      --name aws_http 
      --host ${global_redirectors_aws_us_east.outputs.public_ip} 
      --port 80

  # 任务 3: 注册 Tencent 代理 (仅 prod 模式有效)
  - name: "注册 Tencent 代理节点"
    service: teamserver
    command: >
      ./aggressor_cmd listener_create 
      --name tencent_http 
      --host ${global_redirectors_tencent_sg.outputs.public_ip} 
      --port 80

  # 任务 4: 注册 Aliyun 代理 (仅 prod 模式有效)
  - name: "注册 Aliyun 代理节点"
    service: teamserver
    command: >
      ./aggressor_cmd listener_create 
      --name ali_http 
      --host ${global_redirectors_ali_jp.outputs.public_ip} 
      --port 80
