// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AgentChatStream(arg1, arg2) {
  return window['go']['main']['App']['AgentChatStream'](arg1, arg2);
}

export function AIChatStream(arg1, arg2, arg3) {
  return window['go']['main']['App']['AIChatStream'](arg1, arg2, arg3);
}

export function DeployAgentChatStream(arg1, arg2) {
  return window['go']['main']['App']['DeployAgentChatStream'](arg1, arg2);
}

export function AICostOptimization() {
  return window['go']['main']['App']['AICostOptimization']();
}

export function AIGenerateTemplate(arg1) {
  return window['go']['main']['App']['AIGenerateTemplate'](arg1);
}

export function AIRecommendTemplates(arg1) {
  return window['go']['main']['App']['AIRecommendTemplates'](arg1);
}

export function AnalyzeCaseError(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AnalyzeCaseError'](arg1, arg2, arg3, arg4);
}

export function AnalyzeDeploymentError(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AnalyzeDeploymentError'](arg1, arg2, arg3, arg4);
}

export function BatchDeleteCustomDeployments(arg1) {
  return window['go']['main']['App']['BatchDeleteCustomDeployments'](arg1);
}

export function BatchStartCustomDeployments(arg1) {
  return window['go']['main']['App']['BatchStartCustomDeployments'](arg1);
}

export function BatchStopCustomDeployments(arg1) {
  return window['go']['main']['App']['BatchStopCustomDeployments'](arg1);
}

export function CancelScheduledTask(arg1) {
  return window['go']['main']['App']['CancelScheduledTask'](arg1);
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function CloneCase(arg1, arg2) {
  return window['go']['main']['App']['CloneCase'](arg1, arg2);
}

export function CloneCustomDeployment(arg1, arg2) {
  return window['go']['main']['App']['CloneCustomDeployment'](arg1, arg2);
}

export function CloseTerminal(arg1) {
  return window['go']['main']['App']['CloseTerminal'](arg1);
}

export function ComposeDown(arg1, arg2) {
  return window['go']['main']['App']['ComposeDown'](arg1, arg2);
}

export function ComposePreview(arg1, arg2) {
  return window['go']['main']['App']['ComposePreview'](arg1, arg2);
}

export function ComposeUp(arg1, arg2) {
  return window['go']['main']['App']['ComposeUp'](arg1, arg2);
}

export function CopyFileTo(arg1, arg2) {
  return window['go']['main']['App']['CopyFileTo'](arg1, arg2);
}

export function CopyTemplate(arg1, arg2) {
  return window['go']['main']['App']['CopyTemplate'](arg1, arg2);
}

export function CreateAndRunCase(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateAndRunCase'](arg1, arg2, arg3);
}

export function CreateCase(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateCase'](arg1, arg2, arg3);
}

export function CreateCustomDeployment(arg1) {
  return window['go']['main']['App']['CreateCustomDeployment'](arg1);
}

export function CreateLocalTemplate(arg1, arg2) {
  return window['go']['main']['App']['CreateLocalTemplate'](arg1, arg2);
}

export function CreateProfile(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateProfile'](arg1, arg2, arg3);
}

export function CreateProject(arg1) {
  return window['go']['main']['App']['CreateProject'](arg1);
}

export function CreateRemoteDirectory(arg1, arg2) {
  return window['go']['main']['App']['CreateRemoteDirectory'](arg1, arg2);
}

export function DeleteConfigTemplate(arg1) {
  return window['go']['main']['App']['DeleteConfigTemplate'](arg1);
}

export function DeleteCustomDeployment(arg1) {
  return window['go']['main']['App']['DeleteCustomDeployment'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function DeleteRemoteFile(arg1, arg2) {
  return window['go']['main']['App']['DeleteRemoteFile'](arg1, arg2);
}

export function DeleteTemplateFile(arg1, arg2) {
  return window['go']['main']['App']['DeleteTemplateFile'](arg1, arg2);
}

export function DeployCase(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeployCase'](arg1, arg2, arg3);
}

export function DownloadFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['DownloadFile'](arg1, arg2, arg3);
}

export function EstimateDeploymentCost(arg1) {
  return window['go']['main']['App']['EstimateDeploymentCost'](arg1);
}

export function ExecCommand(arg1, arg2) {
  return window['go']['main']['App']['ExecCommand'](arg1, arg2);
}

export function ExecUserdata(arg1, arg2) {
  return window['go']['main']['App']['ExecUserdata'](arg1, arg2);
}

export function ExportConfigTemplate(arg1, arg2) {
  return window['go']['main']['App']['ExportConfigTemplate'](arg1, arg2);
}

export function ExportTemplates(arg1) {
  return window['go']['main']['App']['ExportTemplates'](arg1);
}

export function FetchRegistryTemplates(arg1) {
  return window['go']['main']['App']['FetchRegistryTemplates'](arg1);
}

export function FetchTemplateReadme(arg1, arg2) {
  return window['go']['main']['App']['FetchTemplateReadme'](arg1, arg2);
}

export function GetActiveProfile() {
  return window['go']['main']['App']['GetActiveProfile']();
}

export function GetBalances(arg1) {
  return window['go']['main']['App']['GetBalances'](arg1);
}

export function GetBaseTemplates() {
  return window['go']['main']['App']['GetBaseTemplates']();
}

export function GetBills(arg1) {
  return window['go']['main']['App']['GetBills'](arg1);
}

export function GetCaseOutputs(arg1) {
  return window['go']['main']['App']['GetCaseOutputs'](arg1);
}

export function GetCasePlanPreview(arg1) {
  return window['go']['main']['App']['GetCasePlanPreview'](arg1);
}

export function GetDeploymentPlanPreview(arg1) {
  return window['go']['main']['App']['GetDeploymentPlanPreview'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetCostEstimate(arg1, arg2) {
  return window['go']['main']['App']['GetCostEstimate'](arg1, arg2);
}

export function GetCurrentProject() {
  return window['go']['main']['App']['GetCurrentProject']();
}

export function GetDeploymentHistory(arg1) {
  return window['go']['main']['App']['GetDeploymentHistory'](arg1);
}

export function GetDisableRightClick() {
  return window['go']['main']['App']['GetDisableRightClick']();
}

export function GetInstanceTypes(arg1, arg2) {
  return window['go']['main']['App']['GetInstanceTypes'](arg1, arg2);
}

export function GetLanguage() {
  return window['go']['main']['App']['GetLanguage']();
}

export function GetMCPStatus() {
  return window['go']['main']['App']['GetMCPStatus']();
}

export function GetNotificationEnabled() {
  return window['go']['main']['App']['GetNotificationEnabled']();
}

export function GetPredictedMonthlyCost() {
  return window['go']['main']['App']['GetPredictedMonthlyCost']();
}

export function GetProviderRegions(arg1) {
  return window['go']['main']['App']['GetProviderRegions'](arg1);
}

export function GetProvidersConfig(arg1) {
  return window['go']['main']['App']['GetProvidersConfig'](arg1);
}

export function GetRemoteFileContent(arg1, arg2) {
  return window['go']['main']['App']['GetRemoteFileContent'](arg1, arg2);
}

export function GetResourceSummary() {
  return window['go']['main']['App']['GetResourceSummary']();
}

export function GetScheduledTask(arg1) {
  return window['go']['main']['App']['GetScheduledTask'](arg1);
}

export function GetShowWelcomeDialog() {
  return window['go']['main']['App']['GetShowWelcomeDialog']();
}

export function GetSSHInfoForCase(arg1) {
  return window['go']['main']['App']['GetSSHInfoForCase'](arg1);
}

export function GetSSHInfosForCase(arg1) {
  return window['go']['main']['App']['GetSSHInfosForCase'](arg1);
}

export function GetTemplateFiles(arg1) {
  return window['go']['main']['App']['GetTemplateFiles'](arg1);
}

export function GetTemplateMetadata(arg1) {
  return window['go']['main']['App']['GetTemplateMetadata'](arg1);
}

export function GetTemplateVariables(arg1) {
  return window['go']['main']['App']['GetTemplateVariables'](arg1);
}

export function GetTerraformMirrorConfig() {
  return window['go']['main']['App']['GetTerraformMirrorConfig']();
}

export function GetTotalRuntime() {
  return window['go']['main']['App']['GetTotalRuntime']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function ImportConfigTemplate(arg1, arg2) {
  return window['go']['main']['App']['ImportConfigTemplate'](arg1, arg2);
}

export function ImportTemplates(arg1) {
  return window['go']['main']['App']['ImportTemplates'](arg1);
}

export function ListAllTemplates() {
  return window['go']['main']['App']['ListAllTemplates']();
}

export function ListCaseScheduledTasks(arg1) {
  return window['go']['main']['App']['ListCaseScheduledTasks'](arg1);
}

export function ListCases() {
  return window['go']['main']['App']['ListCases']();
}

export function ListComposeTemplates() {
  return window['go']['main']['App']['ListComposeTemplates']();
}

export function ListConfigTemplates() {
  return window['go']['main']['App']['ListConfigTemplates']();
}

export function ListCustomDeployments() {
  return window['go']['main']['App']['ListCustomDeployments']();
}

export function ListPortForwards() {
  return window['go']['main']['App']['ListPortForwards']();
}

export function ListProfiles() {
  return window['go']['main']['App']['ListProfiles']();
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function ListRemoteFiles(arg1, arg2) {
  return window['go']['main']['App']['ListRemoteFiles'](arg1, arg2);
}

export function ListScheduledTasks() {
  return window['go']['main']['App']['ListScheduledTasks']();
}

export function ListTemplates() {
  return window['go']['main']['App']['ListTemplates']();
}

export function ListUserdataTemplates() {
  return window['go']['main']['App']['ListUserdataTemplates']();
}

export function LoadConfigTemplate(arg1) {
  return window['go']['main']['App']['LoadConfigTemplate'](arg1);
}

export function PullTemplate(arg1, arg2) {
  return window['go']['main']['App']['PullTemplate'](arg1, arg2);
}

export function RecommendTemplates(arg1) {
  return window['go']['main']['App']['RecommendTemplates'](arg1);
}

export function RemoveCase(arg1) {
  return window['go']['main']['App']['RemoveCase'](arg1);
}

export function RemoveTemplate(arg1) {
  return window['go']['main']['App']['RemoveTemplate'](arg1);
}

export function RenameRemoteFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenameRemoteFile'](arg1, arg2, arg3);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function SaveConfigTemplate(arg1, arg2) {
  return window['go']['main']['App']['SaveConfigTemplate'](arg1, arg2);
}

export function SaveProvidersConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveProvidersConfig'](arg1, arg2, arg3);
}

export function SaveProxyConfig(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveProxyConfig'](arg1, arg2, arg3, arg4);
}

export function SaveTemplateFiles(arg1, arg2) {
  return window['go']['main']['App']['SaveTemplateFiles'](arg1, arg2);
}

export function SaveTerraformMirrorConfig(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveTerraformMirrorConfig'](arg1, arg2, arg3, arg4);
}

export function ScheduleTask(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ScheduleTask'](arg1, arg2, arg3, arg4);
}

export function SelectComposeFile() {
  return window['go']['main']['App']['SelectComposeFile']();
}

export function SelectDirectory(arg1) {
  return window['go']['main']['App']['SelectDirectory'](arg1);
}

export function SelectFile(arg1) {
  return window['go']['main']['App']['SelectFile'](arg1);
}

export function SelectSaveFile(arg1, arg2) {
  return window['go']['main']['App']['SelectSaveFile'](arg1, arg2);
}

export function SetActiveProfile(arg1) {
  return window['go']['main']['App']['SetActiveProfile'](arg1);
}

export function SetDebugLogging(arg1) {
  return window['go']['main']['App']['SetDebugLogging'](arg1);
}

export function SetDisableRightClick(arg1) {
  return window['go']['main']['App']['SetDisableRightClick'](arg1);
}

export function SetNotificationEnabled(arg1) {
  return window['go']['main']['App']['SetNotificationEnabled'](arg1);
}

export function SetSpotMonitorEnabled(arg1) {
  return window['go']['main']['App']['SetSpotMonitorEnabled'](arg1);
}

export function GetSpotMonitorEnabled() {
  return window['go']['main']['App']['GetSpotMonitorEnabled']();
}

export function SetSpotAutoRecoverEnabled(arg1) {
  return window['go']['main']['App']['SetSpotAutoRecoverEnabled'](arg1);
}

export function GetSpotAutoRecoverEnabled() {
  return window['go']['main']['App']['GetSpotAutoRecoverEnabled']();
}

export function GetWebhookConfig() {
  return window['go']['main']['App']['GetWebhookConfig']();
}

export function SetWebhookConfig(arg1) {
  return window['go']['main']['App']['SetWebhookConfig'](arg1);
}

export function TestWebhook(arg1, arg2, arg3) {
  return window['go']['main']['App']['TestWebhook'](arg1, arg2, arg3);
}

export function SetCaseTags(arg1, arg2) {
  return window['go']['main']['App']['SetCaseTags'](arg1, arg2);
}

export function GetAllCaseTags() {
  return window['go']['main']['App']['GetAllCaseTags']();
}

export function GetAllTagNames() {
  return window['go']['main']['App']['GetAllTagNames']();
}

export function SetLanguage(arg1) {
  return window['go']['main']['App']['SetLanguage'](arg1);
}

export function SetShowWelcomeDialog(arg1) {
  return window['go']['main']['App']['SetShowWelcomeDialog'](arg1);
}

export function StartCase(arg1) {
  return window['go']['main']['App']['StartCase'](arg1);
}

export function StartCustomDeployment(arg1) {
  return window['go']['main']['App']['StartCustomDeployment'](arg1);
}

export function StartMCPServer(arg1, arg2) {
  return window['go']['main']['App']['StartMCPServer'](arg1, arg2);
}

export function StartPortForward(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartPortForward'](arg1, arg2, arg3, arg4);
}

export function StartSSHTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartSSHTerminal'](arg1, arg2, arg3);
}

export function StartSSHTerminalInstance(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartSSHTerminalInstance'](arg1, arg2, arg3, arg4);
}

export function StartSSHTerminalDirect(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['StartSSHTerminalDirect'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function StopCase(arg1) {
  return window['go']['main']['App']['StopCase'](arg1);
}

export function StopCustomDeployment(arg1) {
  return window['go']['main']['App']['StopCustomDeployment'](arg1);
}

export function StopMCPServer() {
  return window['go']['main']['App']['StopMCPServer']();
}

export function StopPortForward(arg1) {
  return window['go']['main']['App']['StopPortForward'](arg1);
}

export function SwitchProject(arg1) {
  return window['go']['main']['App']['SwitchProject'](arg1);
}

export function TestTerraformEndpoints() {
  return window['go']['main']['App']['TestTerraformEndpoints']();
}

export function UpdateProfile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateProfile'](arg1, arg2, arg3, arg4);
}

export function UpdateProfileAIConfig(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['UpdateProfileAIConfig'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function UploadFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['UploadFile'](arg1, arg2, arg3);
}

export function UploadUserdataScript(arg1, arg2, arg3) {
  return window['go']['main']['App']['UploadUserdataScript'](arg1, arg2, arg3);
}

export function ValidateDeploymentConfig(arg1) {
  return window['go']['main']['App']['ValidateDeploymentConfig'](arg1);
}

export function ValidateTemplate(arg1) {
  return window['go']['main']['App']['ValidateTemplate'](arg1);
}

export function WriteRemoteFileContent(arg1, arg2, arg3) {
  return window['go']['main']['App']['WriteRemoteFileContent'](arg1, arg2, arg3);
}

export function WriteToTerminal(arg1, arg2) {
  return window['go']['main']['App']['WriteToTerminal'](arg1, arg2);
}

export function GetHTTPServerConfig() {
  return window['go']['main']['App']['GetHTTPServerConfig']();
}

export function SetHTTPServerConfig(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetHTTPServerConfig'](arg1, arg2, arg3, arg4);
}

export function StartHTTPServer(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartHTTPServer'](arg1, arg2, arg3);
}

export function StopHTTPServer() {
  return window['go']['main']['App']['StopHTTPServer']();
}

export function GetHTTPServerStatus() {
  return window['go']['main']['App']['GetHTTPServerStatus']();
}
